language: ruby
sudo: false
env:
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
rvm:
  - 2.1
  - 2.2
  - 2.3
matrix:
  exclude:
    - rvm: 2.1
      env: RAILS_VERSION=master
